import 'package:flutter/material.dart';import 'package:flutter_rating_bar/flutter_rating_bar.dart';import 'package:sakuni/core/app_export.dart';import 'package:sakuni/widgets/app_bar/appbar_image.dart';import 'package:sakuni/widgets/app_bar/appbar_subtitle_4.dart';import 'package:sakuni/widgets/app_bar/custom_app_bar.dart';import 'package:sakuni/widgets/custom_elevated_button.dart';import 'package:sakuni/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class FeedbackScreen extends StatelessWidget {FeedbackScreen({Key? key}) : super(key: key);

TextEditingController messageController = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.primary, resizeToAvoidBottomInset: false, appBar: CustomAppBar(height: getVerticalSize(64), title: CustomElevatedButton(width: getHorizontalSize(174), height: getVerticalSize(37), text: "Feed Back", margin: getMargin(left: 11), leftIcon: Container(margin: getMargin(right: 30), child: CustomImageView(svgPath: ImageConstant.imgArrowleft)), buttonStyle: CustomButtonStyles.none, buttonTextStyle: theme.textTheme.titleLarge!, onTap: () {onTapFeedback(context);}), actions: [AppbarImage(height: getSize(26), width: getSize(26), svgPath: ImageConstant.imgIconoirheadsethelp, margin: getMargin(left: 17, top: 18, right: 19)), AppbarSubtitle4(text: "Help", margin: getMargin(left: 8, top: 22, right: 36, bottom: 2))], styleType: Style.bgFill), body: SizedBox(width: mediaQueryData.size.width, child: SingleChildScrollView(padding: getPadding(top: 64), child: Container(margin: getMargin(left: 19, right: 19, bottom: 5), padding: getPadding(left: 9, top: 32, right: 9, bottom: 32), decoration: AppDecoration.outline11, child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.end, children: [Padding(padding: getPadding(top: 12), child: RatingBar.builder(initialRating: 5, minRating: 0, direction: Axis.horizontal, allowHalfRating: false, itemSize: getVerticalSize(51), itemCount: 5, updateOnDrag: true, onRatingUpdate: (rating) {}, itemBuilder: (context, _) {return Icon(Icons.star);})), CustomTextFormField(controller: messageController, margin: getMargin(top: 53), contentPadding: getPadding(left: 22, top: 19, right: 22, bottom: 19), textStyle: CustomTextStyles.bodyLargeBlack9000116_5, hintText: "Write your words and suggestions to help us improve.", hintStyle: CustomTextStyles.bodyLargeBlack9000116_5, maxLines: 5, filled: true, fillColor: appTheme.gray20001, defaultBorderDecoration: TextFormFieldStyleHelper.outlineBlack900011, enabledBorderDecoration: TextFormFieldStyleHelper.outlineBlack900011, focusedBorderDecoration: TextFormFieldStyleHelper.outlineBlack900011, disabledBorderDecoration: TextFormFieldStyleHelper.outlineBlack900011), CustomElevatedButton(width: getHorizontalSize(193), height: getVerticalSize(63), text: "Submit", margin: getMargin(top: 44), buttonStyle: CustomButtonStyles.fillBlue700, buttonTextStyle: CustomTextStyles.titleMediumPrimary)])))))); } 
/// Navigates to the servicesOneScreen when the action is triggered.
///
/// The [BuildContext] parameter is used to build the navigation stack.
/// When the action is triggered, this function uses the `Navigator` widget
/// to push the named route for the servicesOneScreen.
onTapFeedback(BuildContext context) { Navigator.pushNamed(context, AppRoutes.servicesOneScreen); } 
 }
