import '../save_four_screen/widgets/save_four_item_widget.dart';import 'package:flutter/material.dart';import 'package:sakuni/core/app_export.dart';import 'package:sakuni/widgets/app_bar/appbar_image.dart';import 'package:sakuni/widgets/app_bar/appbar_subtitle.dart';import 'package:sakuni/widgets/app_bar/custom_app_bar.dart';import 'package:sakuni/widgets/custom_elevated_button.dart';class SaveFourScreen extends StatelessWidget {const SaveFourScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.primary, appBar: CustomAppBar(height: getVerticalSize(51), leadingWidth: 52, leading: AppbarImage(height: getSize(37), width: getSize(37), svgPath: ImageConstant.imgArrowleft, margin: getMargin(left: 15, top: 6, bottom: 7), onTap: () {onTapArrowleft5(context);}), title: AppbarSubtitle(text: "Saved", margin: getMargin(left: 30)), actions: [AppbarImage(height: getVerticalSize(24), width: getHorizontalSize(23), svgPath: ImageConstant.imgSearchPrimary24x23, margin: getMargin(left: 16, top: 11, right: 16, bottom: 15))], styleType: Style.bgFill_1), body: Container(width: double.maxFinite, padding: getPadding(left: 12, top: 14, right: 12, bottom: 14), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Padding(padding: getPadding(left: 2, top: 8), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: getPadding(top: 1, bottom: 7), child: Text("1 item selected", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.titleLargeBlack90001)), Spacer(), CustomElevatedButton(width: getHorizontalSize(93), height: getVerticalSize(36), text: "Remove", buttonStyle: CustomButtonStyles.fillRedA40001, buttonTextStyle: theme.textTheme.titleLarge!), CustomElevatedButton(width: getHorizontalSize(86), height: getVerticalSize(36), text: "Unsave", margin: getMargin(left: 5), buttonStyle: CustomButtonStyles.fillCyan300, buttonTextStyle: theme.textTheme.titleLarge!)])), Expanded(child: Padding(padding: getPadding(top: 35), child: GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: getVerticalSize(261), crossAxisCount: 2, mainAxisSpacing: getHorizontalSize(27), crossAxisSpacing: getHorizontalSize(27)), physics: BouncingScrollPhysics(), itemCount: 6, itemBuilder: (context, index) {return SaveFourItemWidget();})))])))); } 


/// Navigates back to the previous screen.
///
/// This function takes a [BuildContext] object as a parameter, which is used
/// to navigate back to the previous screen.
onTapArrowleft5(BuildContext context) { Navigator.pop(context); } 
 }
