import 'package:flutter/material.dart';import 'package:sakuni/core/app_export.dart';import 'package:sakuni/widgets/custom_elevated_button.dart';import 'package:sakuni/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class ServicesDetailsOneDialog extends StatelessWidget {ServicesDetailsOneDialog({Key? key}) : super(key: key);

TextEditingController nameoneController = TextEditingController();

TextEditingController cityController = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return Container(width: getHorizontalSize(349), padding: getPadding(left: 21, top: 23, right: 21, bottom: 23), decoration: AppDecoration.fill1.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.end, children: [Container(width: getHorizontalSize(291), margin: getMargin(top: 9, right: 13), child: Text("To provide you with better service, please kindly confirm your details.", maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: theme.textTheme.titleMedium)), Padding(padding: getPadding(top: 30), child: Text("Name", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.labelMediumBlack90001)), CustomTextFormField(controller: nameoneController, margin: getMargin(top: 6, right: 7), contentPadding: getPadding(left: 18, top: 13, bottom: 13), textStyle: CustomTextStyles.bodySmallBlack90001_1, hintText: "Enter your name", hintStyle: CustomTextStyles.bodySmallBlack90001_1, textInputAction: TextInputAction.next, suffix: Container(margin: getMargin(left: 12, top: 13, right: 10, bottom: 11), child: CustomImageView(svgPath: ImageConstant.imgEdit)), suffixConstraints: BoxConstraints(maxHeight: getVerticalSize(40)), defaultBorderDecoration: TextFormFieldStyleHelper.outlineBlack90001TL5, enabledBorderDecoration: TextFormFieldStyleHelper.outlineBlack90001TL5, focusedBorderDecoration: TextFormFieldStyleHelper.outlineBlack90001TL5, disabledBorderDecoration: TextFormFieldStyleHelper.outlineBlack90001TL5), Padding(padding: getPadding(top: 5), child: Text("Address", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.labelMediumBlack90001)), CustomTextFormField(controller: cityController, margin: getMargin(top: 7, right: 7), contentPadding: getPadding(left: 18, top: 13, bottom: 13), textStyle: CustomTextStyles.bodySmallBlack90001_1, hintText: "Enter your City", hintStyle: CustomTextStyles.bodySmallBlack90001_1, suffix: Container(margin: getMargin(left: 12, top: 12, right: 10, bottom: 12), child: CustomImageView(svgPath: ImageConstant.imgEdit)), suffixConstraints: BoxConstraints(maxHeight: getVerticalSize(40)), defaultBorderDecoration: TextFormFieldStyleHelper.outlineBlack90001TL5, enabledBorderDecoration: TextFormFieldStyleHelper.outlineBlack90001TL5, focusedBorderDecoration: TextFormFieldStyleHelper.outlineBlack90001TL5, disabledBorderDecoration: TextFormFieldStyleHelper.outlineBlack90001TL5), CustomElevatedButton(width: getHorizontalSize(154), height: getVerticalSize(54), text: "Submit", margin: getMargin(top: 45), buttonStyle: CustomButtonStyles.fillBlue700TL27, buttonTextStyle: CustomTextStyles.titleLargeSemiBold, onTap: () {onTapSubmit(context);}, alignment: Alignment.center)])); } 
/// Navigates to the paymentSixScreen when the action is triggered.
///
/// The [BuildContext] parameter is used to build the navigation stack.
/// When the action is triggered, this function uses the `Navigator` widget
/// to push the named route for the paymentSixScreen.
onTapSubmit(BuildContext context) { Navigator.pushNamed(context, AppRoutes.paymentSixScreen); } 
 }
