import '../save_five_screen/widgets/save_five_item_widget.dart';import 'package:flutter/material.dart';import 'package:sakuni/core/app_export.dart';import 'package:sakuni/widgets/app_bar/appbar_image.dart';import 'package:sakuni/widgets/app_bar/appbar_subtitle.dart';import 'package:sakuni/widgets/app_bar/custom_app_bar.dart';import 'package:sakuni/widgets/custom_elevated_button.dart';class SaveFiveScreen extends StatelessWidget {const SaveFiveScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.primary, appBar: CustomAppBar(height: getVerticalSize(51), leadingWidth: 52, leading: AppbarImage(height: getSize(37), width: getSize(37), svgPath: ImageConstant.imgArrowleft, margin: getMargin(left: 15, top: 6, bottom: 7), onTap: () {onTapArrowleft3(context);}), title: AppbarSubtitle(text: "Saved", margin: getMargin(left: 30)), actions: [AppbarImage(height: getVerticalSize(24), width: getHorizontalSize(23), svgPath: ImageConstant.imgSearchPrimary24x23, margin: getMargin(left: 17, top: 14, right: 17, bottom: 12))], styleType: Style.bgFill_1), body: Container(width: double.maxFinite, padding: getPadding(left: 12, right: 12), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Padding(padding: getPadding(left: 2, top: 22), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: getPadding(top: 1, bottom: 7), child: Text("9 items saved", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.titleLargeBlack90001)), CustomElevatedButton(width: getHorizontalSize(96), height: getVerticalSize(36), text: "Select", buttonStyle: CustomButtonStyles.fillBlue700TL2, buttonTextStyle: theme.textTheme.titleLarge!)])), Expanded(child: Padding(padding: getPadding(top: 35), child: GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: getVerticalSize(261), crossAxisCount: 2, mainAxisSpacing: getHorizontalSize(27), crossAxisSpacing: getHorizontalSize(27)), physics: BouncingScrollPhysics(), itemCount: 8, itemBuilder: (context, index) {return SaveFiveItemWidget();})))])))); } 


/// Navigates back to the previous screen.
///
/// This function takes a [BuildContext] object as a parameter, which is used
/// to navigate back to the previous screen.
onTapArrowleft3(BuildContext context) { Navigator.pop(context); } 
 }
