import 'package:flutter/material.dart';import 'package:sakuni/core/app_export.dart';import 'package:sakuni/widgets/app_bar/appbar_image.dart';import 'package:sakuni/widgets/app_bar/appbar_subtitle.dart';import 'package:sakuni/widgets/app_bar/custom_app_bar.dart';class NotificationThreeScreen extends StatelessWidget {const NotificationThreeScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: appTheme.gray300, appBar: CustomAppBar(height: getVerticalSize(64), leadingWidth: 48, leading: AppbarImage(height: getSize(37), width: getSize(37), svgPath: ImageConstant.imgArrowleft, margin: getMargin(left: 11, top: 12, bottom: 14), onTap: () {onTapArrowleft14(context);}), title: AppbarSubtitle(text: "Notification", margin: getMargin(left: 30)), styleType: Style.bgFill_1), body: SizedBox(width: mediaQueryData.size.width, child: SingleChildScrollView(padding: getPadding(top: 19), child: Padding(padding: getPadding(bottom: 5), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Padding(padding: getPadding(left: 20), child: Row(children: [Text("All", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.titleLargeBlack90001), Padding(padding: getPadding(left: 51), child: Text("Offers", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.titleLargeBlack90001))])), CustomImageView(svgPath: ImageConstant.imgLine11, height: getVerticalSize(3), width: getHorizontalSize(32), margin: getMargin(left: 17, top: 4)), Container(width: double.maxFinite, margin: getMargin(top: 49), padding: getPadding(left: 24, top: 9, right: 24, bottom: 9), decoration: AppDecoration.fill1, child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(svgPath: ImageConstant.imgNotificationAmber400, height: getVerticalSize(34), width: getHorizontalSize(35), margin: getMargin(bottom: 50)), Padding(padding: getPadding(left: 14, top: 4, bottom: 56), child: Text("Notification 1", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: theme.textTheme.bodyLarge))]))])))))); } 


/// Navigates back to the previous screen.
///
/// This function takes a [BuildContext] object as a parameter, which is used
/// to navigate back to the previous screen.
onTapArrowleft14(BuildContext context) { Navigator.pop(context); } 
 }
