import 'package:flutter/material.dart';import 'package:sakuni/core/app_export.dart';import 'package:sakuni/widgets/app_bar/appbar_image.dart';import 'package:sakuni/widgets/app_bar/appbar_subtitle.dart';import 'package:sakuni/widgets/app_bar/custom_app_bar.dart';class AddressOneScreen extends StatelessWidget {const AddressOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.primary, appBar: CustomAppBar(height: getVerticalSize(64), leadingWidth: 47, leading: AppbarImage(height: getSize(37), width: getSize(37), svgPath: ImageConstant.imgArrowleft, margin: getMargin(left: 10, top: 12, bottom: 14), onTap: () {onTapArrowleft13(context);}), title: AppbarSubtitle(text: "Address", margin: getMargin(left: 30)), styleType: Style.bgFill_1), body: SizedBox(width: mediaQueryData.size.width, child: SingleChildScrollView(padding: getPadding(top: 29), child: Padding(padding: getPadding(bottom: 5), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Container(width: double.maxFinite, padding: getPadding(left: 29, top: 17, right: 29, bottom: 17), decoration: AppDecoration.txtOutline2, child: Text("+ Add a new address", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.titleMediumBlue700_1)), Container(margin: getMargin(top: 35), padding: getPadding(left: 15, top: 8, right: 15, bottom: 8), decoration: AppDecoration.outline12, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Padding(padding: getPadding(right: 3), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: getPadding(bottom: 1), child: Text("1 Saved address", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.bodyLargeGray40016)), CustomImageView(svgPath: ImageConstant.imgTicket, height: getVerticalSize(21), width: getHorizontalSize(53))])), Padding(padding: getPadding(left: 2, top: 20), child: Text("Pablo Smith", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: theme.textTheme.titleMedium)), Container(width: getHorizontalSize(336), margin: getMargin(left: 2, top: 18, right: 58, bottom: 22), child: Text("HOWRAH, STATION ROAD, GR ROAD, FORSHOR ROAD., HOWRAH, WEST BENGAL, India (IN), Pin Code:- 711101", maxLines: 3, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.bodyLargeBlack9000116_1))]))])))))); } 


/// Navigates back to the previous screen.
///
/// This function takes a [BuildContext] object as a parameter, which is used
/// to navigate back to the previous screen.
onTapArrowleft13(BuildContext context) { Navigator.pop(context); } 
 }
